2024-05-02 17:29:59,434 INFO    MainThread:93862 [wandb_setup.py:_flush():68] Configure stats pid to 93862
2024-05-02 17:29:59,434 INFO    MainThread:93862 [wandb_setup.py:_flush():68] Loading settings from /root/.config/wandb/settings
2024-05-02 17:29:59,434 INFO    MainThread:93862 [wandb_setup.py:_flush():68] Loading settings from /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/settings
2024-05-02 17:29:59,434 INFO    MainThread:93862 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'run_group': 'development', 'project': 'nyc_airbnb'}
2024-05-02 17:29:59,434 WARNING MainThread:93862 [wandb_setup.py:_flush():68] Could not save program above cwd: /root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/bin/pytest
2024-05-02 17:29:59,434 INFO    MainThread:93862 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': None, 'program': '/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/bin/pytest'}
2024-05-02 17:29:59,434 INFO    MainThread:93862 [wandb_init.py:_log_setup():478] Logging user logs to /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_172959-4ylu9rl0/logs/debug.log
2024-05-02 17:29:59,434 INFO    MainThread:93862 [wandb_init.py:_log_setup():479] Logging internal logs to /root/Project-Build-an-ML-Pipeline-Starter/src/data_check/wandb/run-20240502_172959-4ylu9rl0/logs/debug-internal.log
2024-05-02 17:29:59,434 INFO    MainThread:93862 [wandb_init.py:init():518] calling init triggers
2024-05-02 17:29:59,434 INFO    MainThread:93862 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2024-05-02 17:29:59,435 INFO    MainThread:93862 [wandb_init.py:init():571] starting backend
2024-05-02 17:29:59,435 INFO    MainThread:93862 [wandb_init.py:init():575] setting up manager
2024-05-02 17:29:59,436 INFO    MainThread:93862 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-02 17:29:59,438 INFO    MainThread:93862 [wandb_init.py:init():582] backend started and connected
2024-05-02 17:29:59,440 INFO    MainThread:93862 [wandb_init.py:init():670] updated telemetry
2024-05-02 17:29:59,449 INFO    MainThread:93862 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2024-05-02 17:30:59,465 ERROR   MainThread:93862 [wandb_init.py:init():724] backend process timed out, exiting...
encountered error: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2024-05-02 17:30:59,471 ERROR   MainThread:93862 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/root/miniconda3/envs/mlflow-af6473294b18f57ea960125076520147a7a4be59/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    raise error
wandb.errors.CommError: Error communicating with wandb process, exiting...
For more info see: https://docs.wandb.ai/library/init#init-start-error
2024-05-02 17:31:02,869 WARNING MsgRouterThr:93862 [router.py:message_loop():77] message_loop has been closed
